### PR TITLE
New Enumerable methods

### PR DESCRIPTION
**Pull request by JuanDavid31**
### New methods for array objects
- `#my_each` clone method of `Enumerable#each`
- `#my_each_with_index` clone method of `Enumerable#each_with_index`
- `#my_select` clone method of `Enumerable#select`
- `#my_all?` clone method of `Enumerable#all?`
- `#my_none?` clone method of `Enumerable#none?`
- `#my_count` clone method of `Enumerable#count`
- `#my_map` clone method of `Enumerable#map`
- `#my_inject` clone method of `Enumerable#inject`
- `#multyply_els` Method capable of multiplying every element in the array

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 👎🏽** 

Hey Team, Well done with the efforts towards this project. The enumerable pass some tests and are working almost just fine.

REQUIRED CHANGES:

- [ ] `my_each` is not working as the original `each` method, also is not passing all test cases.
- `my_each` should return an Enumerator if no block is given.

- [ ] `my_each_with_index` is not working as the original `each_with_index` method, also is not passing all test cases.
- `my_each_with_index` should return an Enumerator if no block is given.
- it returns the array/range/hash itself if a block is given.
```
    [1, 2, 3].each_with_index { |num, idx| num }
     [1, 2, 3]
    (1..3).each { |num, idx| num * idx }
    1..3
```

- [ ] `my_select` is not working as the original `select` method, also is not passing all test cases.
- `my_select` should return an Enumerator if no block is given.

- [ ] `my_all?` should behave just like `all?`. It should be able to accept arguments passed to it.
- `my_all?` is currently throwing ArgumentError when I pass in arguments to the method.
- Happens to all integers, Numerics, regex, class passed as arguments. `Given 1, expected 0`


- [ ] `my_any?` should behave just like `any?`. It should be able to accept arguments passed to it.
- `my_any?` is currently throwing ArgumentError when I pass in arguments to the method.
- Happens to all integers, Numerics, regex, class passed as arguments. `Given 1, expected 0`

- [ ] `my_none?` should return true if the block never returns true for all elements. Also when no block or argument is given returns true only if none of the collection members is true.
```
expected: true
             got: false

```
-` my_none?` returns false if the block ever returns true for all elements
```
 expected: false
             got: true
```
- [ ] `my_none?` should behave just like `none?`. It should be able to accept arguments passed to it.
- `my_none?` is currently throwing ArgumentError when I pass in arguments to the method.
- Happens to all integers, Numerics, regex, class passed as arguments. `Given 1, expected 0`


- [ ] `my_map?` should behave just like `map?`. It should be able to accept arguments passed to it.
- `my_map?` is currently throwing ArgumentError when I pass in arguments to the method.
- executes only the proc when both a block and a proc are given. `Given 1, expected 0`
- `my_map` should return an Enumerator if no block is given

- [ ] `my_inject` is expected to raise a "LocalJumpError" when no block or argument is given.
- `my_inject` is not performing these operations.
```
Failure/Error: expect(array.my_inject(:+)).to eq array.inject(:+)
      
        expected: 421
             got: [5, 2, 1, 2, 2, 6, 7, 6, 4, 8, 1, 1, 5, 2, 6, 6, 5, 6, 1, 2, 0, 2, 6, 4, 3, 6, 4, 7, 5, 2, 0, 7, 0, 0..., 4, 6, 4, 6, 8, 5, 3, 0, 2, 1, 4, 3, 2, 6, 6, 5, 4, 0, 2, 6, 0, 8, 5, 0, 7, 8, 2, 7, 7, 8, 6, 3, 8]

```
```
 Failure/Error: expect(range.my_inject(:*)).to eq range.inject(:*)
      
        expected: 1267253883404724085150525340252698701849068398706688000000000000
             got: 5..50

```
### Kindly make all the necessary changes 💯  and submit for another code review.

**Happy Coding!!** 👍🏽 

Reach me on slack for more inquiries: **Roy Mukuye**

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Required Changes 🛑♻**

<hr>

Hello there, great job you've done on this project so far. However, there are still few changes left need to be done in order to get this PR approved.

<hr>

- [x] my_all? method  ```puts [1, 3.14, 42].my_all?(Numeric)``` should print true. Instead, it printed false
- [ ] my_any? method ```puts [nil, true, 99].my_any?(Integer)``` should print true. Instead, it printed false
- [ ] my_none? method ```puts %w[ant bear cat].my_none? {|word| word.length == 5}``` should print true. Instead, it printed false
- [ ] my_none? method ```puts %w[ant bear cat].my_none?(/d/)``` should print true. Instead, it printed false
- [ ] my_none? method ```puts [nil].my_none?``` and ```puts [nil, false].my_none?``` should print true. Instead, they printed false
- [ ] multiply_els method should accept arguments. Please make sure to add multiply_els(arg goes here) and fix the code to match that change. ```puts multiply_els([2,4,5])``` should print out 40

<hr>

Kindly make the above fixes and submit for a re-review.
Good luck and happy coding 👨‍💻💻😊

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED!! :recycle: :red_circle: 
-----------------
Hello team!! :wave: you are doing an amazing job with the required changes.
You have to work on a few changes :hammer_and_wrench: see it below :point_down: 
-------------

- [x] In GitHub remember that you should set up your development branch as a default branch in your repository. It’s the way that almost every development team in the world works, so this will definitely benefit your chances of landing your first job. [Here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/) you can refresh on how to make it. 

- [x] #my_all? when no block or argument is given returns true when none of the collection members are false or nil. Instead is returning False. 
- [ ] #my_all? when a Regex is passed as an argument returns false if any of the collection does not match the Regex. Instead is returning True.
- [ ] #my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern. Instead is returning True.
- [ ] #my_any? when a Regex is passed as an argument returns true if any of the collection matches the Regex. Instead is returning False.
- [ ] #my_none? when a Regex is passed as an argument returns false if any of the collection matches the Regex. instead is returning True.
- [x] #my_count? you having a problem with the `.length` changes it for `.size` and it will solve it.
---------
Make the required changes and send it to another review. :wrench: :muscle: 
HAPPY CODDING !!!

**Review by oloomoses — CHANGES_REQUESTED** [review]
# Status: Changes required
Hello team you are doing great with the changes request. You are almost there :muscle:
Kindly fix the below changes before this project can be approved. 
- [ ] #my_each_with_index when a block is given when self is a range returns the range itself after calling the given block once for each element in self
- [ ] #my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.

- [ ] #my_inject when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block::range

- [ ] #my_inject when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method

### fee free to contact me on slack [Oloo Moses] incase of doubts or concerns

**Review by oloomoses — APPROVED** [review]
# Hello Team Congratulation! Project Approved :muscle: :tada: :clap: 
You have done a fantastic job with the changes. You have met all the requirements for this project. Feel free to merge and close this pull request.
I wish you the best on your next project and see you at the top :rocket:

**Pull request merged**
